export interface Scholarship {
  batch: string,
  degree: string,
  fullName: string,
  address: string,
  regNumber: string,
  contactNumber: string,
  email: string,
  divisionGramasevaNiladhari: string,
  distance: string,
  district: string,

  brother1Name: string,
  brother1Age: string,
  brother1CivilStatus: string,
  brother1University: string,

  brother2Name: string,
  brother2Age: string,
  brother2CivilStatus: string,
  brother2University: string,

  brother3Name: string,
  brother3Age: string,
  brother3CivilStatus: string,
  brother3University: string,

  brother4Name: string,
  brother4Age: string,
  brother4CivilStatus: string,
  brother4University: string,

  brother5Name: string,
  brother5Age: string,
  brother5CivilStatus: string,
  brother5University: string,

  Owner1Name:string,
  Owner1Relationship:string,
  Owner1Location:string,
  Owner1Cultivation:string,
  Owner1Extent:string,
  Owner1Income:string,

  Owner2Name:string,
  Owner2Relationship:string,
  Owner2Location:string,
  Owner2Cultivation:string,
  Owner2Extent:string,
  Owner2Income:string,

  Owner3Name:string,
  Owner3Relationship:string,
  Owner3Location:string,
  Owner3Cultivation:string,
  Owner3Extent:string,
  Owner3Income:string,

  Owner4Name:string,
  Owner4Relationship:string,
  Owner4Location:string,
  Owner4Cultivation:string,
  Owner4Extent:string,
  Owner4Income:string
}
