export class RegScho {
    constructor(
        public batch:string,
        public degree: string,
        public fullName: string,
        public address: string,
        public regNumber: string,
        public contactNumber: string,
        public email: string,
        public divisionGramasevaNiladhari: string,
        public distance: string,
        public district: string,
        public ReasonForApplyingScholarship: string,
        public OtherScholarship: string,
        public Samurdhi: string, 
        public brother1Name:string,
        public brother1Age:string,
        public brother1CivilStatus:string,
        public brother1University:string,
        public brother2Name:string,
        public brother2Age:string,
        public brother2CivilStatus:string,
        public brother2University:string,
        public brother3Name:string,
        public brother3Age:string,
        public brother3CivilStatus:string,
        public brother3University:string,
        public brother4Name:string,
        public brother4Age:string,
        public brother4CivilStatus:string,
        public brother4University:string,
        public brother5Name:string,
        public brother5Age:string,
        public brother5CivilStatus:string,
        public brother5University:string,
        public Owner1Name:string,
        public Owner1Relationship:string,
        public Owner1Location:string,
        public Owner1Cultivation:string,
        public Owner1Extent:string,
        public Owner1Income:string,
        public Owner2Name:string,
        public Owner2Relationship:string,
        public Owner2Location:string,
        public Owner2Cultivation:string,
        public Owner2Extent:string,
        public Owner2Income:string,
        public Owner3Name:string,
        public Owner3Relationship:string,
        public Owner3Location:string,
        public Owner3Cultivation:string,
        public Owner3Extent:string,
        public Owner3Income:string,
        public Owner4Name:string,
        public Owner4Relationship:string,
        public Owner4Location:string,
        public Owner4Cultivation:string,
        public Owner4Extent:string,
        public Owner4Income:string,
        public House1Owner:string,
        public House1Relationship:string,
        public House1AssessmentNo:string,
        public House1OwnerNo:string,
        public House1Address:string,
        public House1AnualIncome:string,
        public House1RentDetail:string,
        public House2Owner:string,
        public House2Relationship:string,
        public House2AssessmentNo:string,
        public House2OwnerNo:string,
        public House2Address:string,
        public House2AnualIncome:string,
        public House2RentDetail:string,
        public House3Owner:string,
        public House3Relationship:string,
        public House3AssessmentNo:string,
        public House3OwnerNo:string,
        public House3Address:string,
        public House3AnualIncome:string,
        public House3RentDetail:string,
        public WorkingPlace:string,
        public WorkingPost:string,
        public WorkingSalaryScale:string,
        public WorkingSalary:string,
        public WorkingAppointment:string,
        public MarriageData:string,
        public Spouse:string,
        public SpouseInstitution:string,
        public SpousePost:string,
        public PresentSalary:string,
        public SriLankanCitizen:string,
        public FatherName:string,
        public FatherLiving:string,
        public FatherYear:string,
        public FatherMonth:string,
        public FatherEmployee:string,
        public FatherEmployeeAddress:string,
        public FatherPension:string,
        public FatherHousesProperties:string,
        public FatherOtherSources:string,
        public FatherAnualIncome:string,
        public MotherName:string,
        public MotherLiving:string,
        public MotherYear:string,
        public MotherMonth:string,
        public MotherEmployee:string,
        public MotherEmployeeAddress:string,
        public MotherPension:string,
        public MotherHousesProperties:string,
        public MotherOtherSources:string,
        public MotherAnualIncome:string,
        public FatherMotherTotalIncome:string,
        public GuardianName:string,
        public GuardianAge:string,
        public GuardianAddress:string,
        public GuardianEmployedPost:string,
        public GuardianAnualSalary:string,
        public GuardianAnualIncome:string

    ) { }
}


