export class RegScho {
    constructor(
        public batch:string,
        public degree: string,
        public fullName: string,
        public address: string,
        public regNumber: string,
        public contactNumber: string,
        public email: string,
        public divisionGramasevaNiladhari: string,
        public distance: string,
        public district: string,
        public ReasonForApplyingScholarship: string,
        public OtherScholarship: string,
        public Samurdhi: string, 
        public brother1Name:string,
        public brother1Age:string,
        public brother1CivilStatus:string,
        public brother1University:string,
        public brother2Name:string,
        public brother2Age:string,
        public brother2CivilStatus:string,
        public brother2University:string,
        public brother3Name:string,
        public brother3Age:string,
        public brother3CivilStatus:string,
        public brother3University:string,
        public brother4Name:string,
        public brother4Age:string,
        public brother4CivilStatus:string,
        public brother4University:string,
        public brother5Name:string,
        public brother5Age:string,
        public brother5CivilStatus:string,
        public brother5University:string,
        public Owner1Name:string,
        public Owner1Relationship:string,
        public Owner1Location:string,
        public Owner1Cultivation:string,
        public Owner1Extent:string,
        public Owner1Income:string,
        public Owner2Name:string,
        public Owner2Relationship:string,
        public Owner2Location:string,
        public Owner2Cultivation:string,
        public Owner2Extent:string,
        public Owner2Income:string,
        public Owner3Name:string,
        public Owner3Relationship:string,
        public Owner3Location:string,
        public Owner3Cultivation:string,
        public Owner3Extent:string,
        public Owner3Income:string,
        public Owner4Name:string,
        public Owner4Relationship:string,
        public Owner4Location:string,
        public Owner4Cultivation:string,
        public Owner4Extent:string,
        public Owner4Income:string
    ) { }
}


